name: fpmi_music_band
description: FPMI Flutter Music Band

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  core:
    path: core
  core_ui:
    path: core_ui
  data:
    path: data
  domain:
    path: domain

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
