name: fpmi_music_band
description: FPMI Flutter Music Band

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^2.16.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  core:
    path: core
  core_ui:
    path: core_ui
  data:
    path: data
  domain:
    path: domain
  shared_dependencies:
    path: shared_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/resources/en.json
    - assets/resources/ru.json

  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets/fonts/sf-ui/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/sf-ui/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/sf-ui/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/sf-ui/SFUIDisplay-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
            - asset: assets/fonts/roboto/Roboto-Medium.ttf
              weight: 500
