name: discover
description: A new Flutter package project.
homepage:
publish_to: 'none'

environment:
  sdk: ^2.17.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fpmi_music_band:
    path: ../../

  shared_dependencies:
    path: ../../shared_dependencies


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
