name: discover
description: A new Flutter package project.
homepage:
publish_to: 'none'

environment:
  sdk: ^2.17.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  
  domain:
    path: ../../domain

  data:
    path: ../../data

  core_ui:
    path: ../../core_ui

  fpmi_music_band:
    path: ../../

  shared_dependencies:
    path: ../../shared_dependencies

  carousel_slider: ^4.1.1
  rxdart: ^0.27.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
