name: shared_dependencies
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ^2.16.2
  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  mockito: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: