name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  intl: ^0.17.0

  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  firebase_crashlytics: ^2.6.3
  firebase_analytics: ^9.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
