name: core
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^2.16.2

dependencies:
  get_it: ^7.2.0
  shared_dependencies:
    path: ../shared_dependencies
  fpmi_music_band:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
