name: domain
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^2.16.2

dependencies:
  shared_dependencies:
    path: ../shared_dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: