name: domain
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^2.16.2
  flutter: ^1.17.0

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  
  data:
    path: ../data

  shared_dependencies:
    path: ../shared_dependencies
  
  mockito: ^5.2.0
  
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter: